<link href="<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)?>frontend/base/default/css/onepagecheckout.css" rel="stylesheet">
<script type="text/javascript" src="<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)?>frontend/base/default/deivison/jquery.maskedinput.min.js"></script>
<script type="text/javascript" src="<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)?>frontend/base/default/deivison/jquery.autotab-1.1b.js"></script>
<script type="text/javascript" src="<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)?>frontend/base/default/deivison/deivison.js"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>Tulipa-Checkout/jquery.blockUI.js"></script>
<link href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>Tulipa-Checkout/skins/square/grey.css" rel="stylesheet">
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>Tulipa-Checkout/icheck.min.js"></script>
<link href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>Tulipa-Checkout/bootstrap.min.css" rel="stylesheet">
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>Tulipa-Checkout/bootstrap.min.js"></script>
<link href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>Tulipa-Checkout/jquery.fancybox.css" rel="stylesheet">
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>Tulipa-Checkout/jquery.fancybox.js"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>Tulipa-Checkout/cnpj.js"></script>
<link href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>Tulipa-Checkout/completer.min.css" rel="stylesheet">
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>Tulipa-Checkout/completer.min.js"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>Tulipa-Checkout/pGenerator.jquery.js"></script>
<script>
jQuery.blockUI({
            message: 'Carregando, aguarde...',
			css: {border: 'none', backgroundColor: 'none', color: '#fff' }
        	});
</script>
<div class="page-title">
    <h1 class='h1_opc'><?php echo Mage::getStoreConfig('onepagecheckout/general/title') ?></h1>
    <?php echo $this->__('Fill in the fields below to complete your purchase!') ?>
    <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()){ ?>
    <?php
    $guest_checkout1 = Mage::getStoreConfig('onepagecheckout/general/guest_checkout1');
    if ($guest_checkout1 === '1') : ?>
    <p class="onepagecheckout_loginarea">
        <!--a href="javascript:void(0)" class="fancybox onepagecheckout_loginlink" onclick='open_login();'>-->
        <a href="#onepagecheckout_loginbox" id="fancyLink" class="onepagecheckout_loginlink">
            <?php echo $this->__('Already registered? Click here to login') ?>
        </a>
    </p>
    <?php endif; ?>
    <?php
    $guest_checkout2 = Mage::getStoreConfig('onepagecheckout/general/guest_checkout2');    
    if ($guest_checkout2 === '1') : ?>
    <p class="onepagecheckout_loginarea">
        <a href="<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>customer/account/login/" class="onepagecheckout_loginlink" >
            <?php echo $this->__('Already registered? Click here to login') ?>
        </a>
    </p>
    <?php endif; ?>
	<?php 
	
		echo $this->getChildHtml('customer.login');
		echo $this->getChildHtml('customer.forgot');
    }    
    ?>
</div>
<div class='ptdivline'>
	<img src="<?php echo $this->getSkinUrl('images/onepagecheckout/titulo-onestepcheckout.gif') ?>" />
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php
$seq_http	= (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on'); 
?>
<script type="text/javascript">
	var http_type	= '<?php if($seq_http){echo 'https';}else{echo 'http';}?>';
</script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/onepagecheckout.js') ?>"></script>
<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<form action="" id="onepagecheckout_orderform">
<div class="col3-set onepagecheckout_datafields">
    <div class="col-1">
        <?php echo $this->getChildHtml('billing.address') ?>
        <?php echo $this->getChildHtml('shipping.address') ?>
    </div>
    <div class="col-2">
    	<a name="frete"></a>
        <?php echo $this->getChildHtml('shipping.method') ?>
		<a name="pagamento"></a>
        <?php echo $this->getChildHtml('payment.method') ?>
        <a name="cupom"></a>
         <div id="checkout-coupon-discount-load">
            <?php echo $this->getChildHtml('coupon') ?>
        </div>
        <?php if (Mage::getStoreConfig('onepagecheckout/general/comment')) : ?>
		<div class="op_block_title">
	    	<?php echo $this->helper('sales')->__('Comment') ?>
	    </div>      
        <div class="form_fields">
            <div class="full">
                <div class="data_area" id='comment-block'>
                    <textarea name="order-comment" id="order-comment"><?php echo trim(Mage::getSingleton('customer/session')->getOrderCustomerComment()) ?></textarea>
                </div>
            </div>
        </div>
        <?php endif; ?>
        
		<?php if (Mage::helper('onepagecheckout')->isSubscribeNewAllowed()) : ?>
            <p class="newsletter">
                <input checked="checked" type="checkbox" id="newsletter-signup" name="newsletter" value="1" title="<?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?>" class="checkbox" />
                <label for="newsletter-signup">
                    <?php echo "Receba nossas ofertas"//Mage::helper('newsletter')->__('Sign up for our newsletter') ?>
                </label>
            </p>
        <?php endif; ?>
    </div>
    <div class="col-3">
   		<a name="resumocompra"></a>
        <?php echo $this->getChildHtml('review') ?>
    </div>
</div>
</form>
<!-- consulta cnpj -->
<div id="consultaexterna"></div>
<script type="text/javascript">
//<![CDATA[
    var checkout = new OPC('onepagecheckout_orderform', {
    	save    : '<?php echo $this->getUrl('onepagecheckout/index/saveOrder', array('_secure'=>$seq_http)) ?>',
    	update  : '<?php echo $this->getUrl('onepagecheckout/index/updateCheckout', array('_secure'=>$seq_http)) ?>',
        success : '<?php echo $this->getUrl('onepagecheckout/index/success', array('_secure'=>$seq_http)) ?>',
        failure : '<?php echo $this->getUrl('checkout/cart') ?>'
    }, "<?php echo $this->__('Please agree to all the terms and conditions.') ?>");
    document.observe("dom:loaded", function() {
        var win_triggers	= Array();
   		$$('.checkout-agreements .agree a').each(function(item){
   			var obj	= {
   				el: $$('.' + item.className),
   		   		event: 'click',
				window: $(item.className + '-window')
			};
   			win_triggers.push(obj);
        });
		opc_window	= new OPC.Window({triggers: win_triggers});
    });
//]]>
</script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>Tulipa-Checkout/paranaue.js"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>Tulipa-Checkout/tipo.js"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>Tulipa-Checkout/checkout.js"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>Tulipa-Checkout/inputs.js"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>Tulipa-Checkout/forcapass.js"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>Tulipa-Checkout/gerasenha.js"></script>
<style>
.total-flutuante{ position:absolute; right:0px; z-index:2; background:#fff;}
</style>
<script>
/*var largjanela;
function tamjanela(){ //called on viewer reload, screen resize or scroll
    largjanela = jQuery(window).width(); //retrieve current window width
};
tamjanela();
jQuery(window).resize(function() {
  tamjanela();
});
jQuery(window).scroll(function() {
	  if(largjanela>960){
		if(jQuery(this).scrollTop()>300){
			altura=jQuery(this).scrollTop();
			altura=altura-350;
			jQuery('div.col-3').addClass('total-flutuante');
			jQuery('div.col-3').css('top',altura+'px');
		}
		else{
			jQuery('div.col-3').removeClass('total-flutuante');
		}

	}else{
		jQuery('div.col-3').removeClass('total-flutuante');
		}
});	*/ 
//login com fancybox
jQuery("a#fancyLink,a.onepagecheckout_loginlink").fancybox({
        'href'   : '#onepagecheckout_loginbox',
        'titleShow'  : false,
        'transitionIn'  : 'elastic',
        'transitionOut' : 'elastic'
    });
jQuery("a#esquecilink").fancybox({
        'href'   : '#onepagecheckout_forgotbox',
        'titleShow'  : false,
        'transitionIn'  : 'elastic',
        'transitionOut' : 'elastic'
    });
</script>